### PR TITLE
7903784: NullPointerException: Cannot read the array length because the return value of "java.io.File.listFiles()" is null

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which proposes to address NullPointerException(s) as noted in https://bugs.openjdk.org/browse/CODETOOLS-7903784?

The commit here introduces null checks to the remaining usages of `File.listFiles()` call in `ScratchDirectory`. This is similar to what we did for https://bugs.openjdk.org/browse/CODETOOLS-7903538.

No new test has been introduced given the nature of this change. Existing tests continue to pass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [CODETOOLS-7903784](https://bugs.openjdk.org/browse/CODETOOLS-7903784): NullPointerException: Cannot read the array length because the return value of "java.io.File.listFiles()" is null (**Bug** - P4)

### Reviewers
 * [Christian Stein](https://openjdk.org/census#cstein) (@sormuras - Committer)
 * [Jan Lahoda](https://openjdk.org/census#jlahoda) (@lahodaj - Author)
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jtreg.git pull/218/head:pull/218` \
`$ git checkout pull/218`

Update a local copy of the PR: \
`$ git checkout pull/218` \
`$ git pull https://git.openjdk.org/jtreg.git pull/218/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 218`

View PR using the GUI difftool: \
`$ git pr show -t 218`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jtreg/pull/218.diff">https://git.openjdk.org/jtreg/pull/218.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jtreg/pull/218#issuecomment-2275055636)

### CODE REVIEW

**Review by sormuras — APPROVED** [review]
Looks null-safe to me.

**Review by lahodaj — APPROVED** [review]
Looks reasonable to me.

**Review by jonathan-gibbons — APPROVED** [review]

**Comment by jaikiran** [comment]
Thank you all for the reviews.

**Pull request closed without merging**
