### PR TITLE
7903752: Include duration information in JUnit-based tests

### PR DESCRIPTION
**Pull request by sormuras**
Please review this change to include duration information in JUnit-based tests.

For example, see this excerpt from a `.jtr` file generated for the `JupiterTests` self-test.

Before:
```
#section:junit
...
----------System.err:(21/1306)----------
STARTED    JupiterTests::nullEmptyAndBlankStrings '[1] test('null')'
SUCCESSFUL JupiterTests::nullEmptyAndBlankStrings '[1] test('null')'
STARTED    JupiterTests::nullEmptyAndBlankStrings '[2] test('')'
SUCCESSFUL JupiterTests::nullEmptyAndBlankStrings '[2] test('')'
...
```
After:
```
#section:junit
...
----------System.err:(21/1306)----------
STARTED    JupiterTests::nullEmptyAndBlankStrings '[1] test('null')'
SUCCESSFUL JupiterTests::nullEmptyAndBlankStrings '[1] test('null')' [24ms]
STARTED    JupiterTests::nullEmptyAndBlankStrings '[2] test('')'
SUCCESSFUL JupiterTests::nullEmptyAndBlankStrings '[2] test('')' [1ms]
...
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [CODETOOLS-7903752](https://bugs.openjdk.org/browse/CODETOOLS-7903752): Include duration information in JUnit-based tests (**Enhancement** - P4)

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jtreg.git pull/206/head:pull/206` \
`$ git checkout pull/206`

Update a local copy of the PR: \
`$ git checkout pull/206` \
`$ git pull https://git.openjdk.org/jtreg.git pull/206/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 206`

View PR using the GUI difftool: \
`$ git pr show -t 206`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jtreg/pull/206.diff">https://git.openjdk.org/jtreg/pull/206.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jtreg/pull/206#issuecomment-2165145671)

### CODE REVIEW

**Comment by pavelrappo** [comment]
I'm not an official reviewer here, but thanks for doing this. And thanks for using `System.nanoTime()`. Because we didn't have this feature, I had to write something similar ad-hoc in https://github.com/openjdk/jdk/pull/19627.

**Comment by jaikiran** [comment]
Hello Christian, the proposed change looks good to me, especially the way its reported. 
Would you want to also include this same thing for testng too? Here's what I experimented for testng:
```diff
diff --git a/src/share/classes/com/sun/javatest/regtest/agent/TestNGRunner.java b/src/share/classes/com/sun/javatest/regtest/agent/TestNGRunner.java
index 713b12e..d32dbec 100644
--- a/src/share/classes/com/sun/javatest/regtest/agent/TestNGRunner.java
+++ b/src/share/classes/com/sun/javatest/regtest/agent/TestNGRunner.java
@@ -185,12 +185,13 @@ public class TestNGRunner implements MainActionHelper.TestRunner {
             } else {
                 suffix = "\n";
             }
-
+            long durationMillis = itr.getEndMillis() - itr.getStartMillis();
             System.out.print(k.toString().toLowerCase()
                     + " " + itr.getMethod().getConstructorOrMethod().getDeclaringClass().getName()
                     + "." + itr.getMethod().getMethodName()
                     + formatParams(itr)
                         + ": " + statusToString(itr.getStatus())
+                        + " [" + durationMillis + "ms]"
                         + suffix);
         }

```

and testng tests with jtreg now report as follow (similar to junit):

```
test LargeEntriesTest.testForceZIP64End(java.util.ImmutableCollections$MapN@1398b884, 8): success [141ms]
test LargeEntriesTest.testForceZIP64End(java.util.ImmutableCollections$MapN@1caef225, 0): success [5ms]
test LargeEntriesTest.testForceZIP64End(java.util.ImmutableCollections$MapN@2a2df4a5, 8): success [4ms]
test LargeEntriesTest.testForceZIP64End(java.util.ImmutableCollections$MapN@85ce7c1, 0): success [3ms]
test LargeEntriesTest.testJar({create=true}, 8): success [5121ms]
test LargeEntriesTest.testJar(java.util.ImmutableCollections$MapN@34771e2b, 0): success [3029ms]
test LargeEntriesTest.testJar(java.util.ImmutableCollections$MapN@27fb5d9f, 8): success [4333ms]
test LargeEntriesTest.testZip({create=true}, 8): success [3944ms]
test LargeEntriesTest.testZip(java.util.ImmutableCollections$MapN@62272fdb, 0): success [2638ms]
test LargeEntriesTest.testZip(java.util.ImmutableCollections$MapN@6f1bd253, 8): success [4138ms]
```

**Comment by jaikiran** [comment]
If you think the testng changes should be done in a separate issue that's fine with me. I just noticed that with that change to testng runner, the self tests in jtreg fail because of mismatch in the text output and those will need an update.

**Comment by sormuras** [comment]
> Would you want to also include this same thing for testng too? Here's what I experimented for testng: [...]

That makes sense for existing TestNG-based tests, too. So, yes, let's include duration information there as well - in a dedicated issue, as you suggested.

Note that new tests should be written using JUnit Jupiter API: https://bugs.openjdk.org/browse/JDK-8307843

**Comment by jaikiran** [comment]
For similar changes in testng, I have created https://bugs.openjdk.org/browse/CODETOOLS-7903753 and opened a PR with the proposed changes.

**Review by mcimadamore — APPROVED** [review]

**Pull request closed without merging**
