### PR TITLE
7903499: Update various versions used by jtreg's IDEA plugin

### PR DESCRIPTION
**Pull request by Siedlerchr**
This enables building the plugin with never java versions

I tested with IntelliJ 2023.1.2 and java 17 and 19

Plugin still works

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [CODETOOLS-7903499](https://bugs.openjdk.org/browse/CODETOOLS-7903499): Update various versions used by jtreg's IDEA plugin (**Enhancement** - P4)

### Reviewers
 * [Christian Stein](https://openjdk.org/census#cstein) (@sormuras - Committer) ⚠️ Review applies to [18b80028](https://git.openjdk.org/jtreg/pull/157/files/18b8002863b260fdc4173dd0efe98c6cedd6b73f)
 * [Maurizio Cimadamore](https://openjdk.org/census#mcimadamore) (@mcimadamore - Committer) ⚠️ Review applies to [18b80028](https://git.openjdk.org/jtreg/pull/157/files/18b8002863b260fdc4173dd0efe98c6cedd6b73f)
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**) ⚠️ Review applies to [18b80028](https://git.openjdk.org/jtreg/pull/157/files/18b8002863b260fdc4173dd0efe98c6cedd6b73f)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jtreg.git pull/157/head:pull/157` \
`$ git checkout pull/157`

Update a local copy of the PR: \
`$ git checkout pull/157` \
`$ git pull https://git.openjdk.org/jtreg.git pull/157/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 157`

View PR using the GUI difftool: \
`$ git pr show -t 157`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jtreg/pull/157.diff">https://git.openjdk.org/jtreg/pull/157.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jtreg/pull/157#issuecomment-1598410478)

### CODE REVIEW

**Comment by Siedlerchr** [comment]
> ⚠️ Executable files are not allowed (file: plugins/idea/gradlew) 

Well that is a problem because updating gradle incldues a binary

**Comment by sormuras** [comment]
It's not the binary causing an issue, it's the executable bit in `plugins/idea/gradlew`. Please revert the file access modifiers - but keep the content.

Would you please update the Gradle version to 7.6.1 and include the SHA256 checksum of the Gradle Wrapper in the `gradle/wrapper/gradle-wrapper.properties` file? Find checksums here: https://gradle.org/release-checksums/

I'll address the "Commit message must refer to an issue" separately.

**Comment by sormuras** [comment]
Thanks for updating the PR, @Siedlerchr 

I created https://bugs.openjdk.org/browse/CODETOOLS-7903499 to track this change.

Please edit the title of this PR to read: `7903499: Update various versions used by jtreg's IDEA plugin`

**Review by sormuras — APPROVED** [review]
With changes of

- #160 and
- #159

being integrated, this PR can integrated as well.

**Comment by mcimadamore** [comment]
I tried the branch - it all works very well. One minor note: we should update the README file to say that developers need to set JAVA_HOME to a suitable Java version (e.g. 17 or later), otherwise gradle might pick up a different version and fail.

**Review by mcimadamore — APPROVED** [review]

**Comment by sormuras** [comment]
Thanks for the review, Maurizio!

I wonder if we can apply something similar to https://github.com/junit-team/junit5/blob/649c9a85fe99087cca9335f3b4cd8024750695c9/gradle/plugins/settings.gradle.kts#L1-L5 in order to enforce a suitable Java version? /cc @marcphilipp

**Comment by marcphilipp** [comment]
As far as I can tell the `javaLevel` property is currently only used to configure the source/target compatibility of Java compile tasks:

https://github.com/openjdk/jtreg/blob/4b756c42fb9c06bcffe5e6de2312b787d4c9a6f2/plugins/idea/build.gradle#L14-L17

Instead, the `options.release` option should be used since `-source` and `-target` are deprecated IIRC.

> I wonder if we can apply something similar to [junit-team/junit5@`649c9a8`/gradle/plugins/settings.gradle.kts#L1-L5](https://github.com/junit-team/junit5/blob/649c9a85fe99087cca9335f3b4cd8024750695c9/gradle/plugins/settings.gradle.kts#L1-L5) in order to enforce a suitable Java version? /cc @marcphilipp

That concerns the version of Java the build is running with which doesn't necessarily have to be the same that is used for compilation. In JUnit we mainly restrict the version the build runs with to ensure a version of Java that is supported by Gradle is used and to benefit from Gradle's build cache across different machines. If everyone used a different major version of Java, that would result in different cache keys.

**Review by jonathan-gibbons — APPROVED** [review]
Approved, based on @mcimadamore review

**Comment by sormuras** [comment]
After integrating https://github.com/openjdk/jtreg/commit/a396e2f85d64e245f82269eed4d7d2b662c030b0 this PR does not longer apply cleanly. @Siedlerchr can you please resolve the conflicts on your branch? Happy to sponsor the PR afterwards.

**Pull request closed without merging**
