### PR TITLE
7902912: Update IntelliJ Plugin build Readme

### PR DESCRIPTION
**Pull request by tstuefe**
Hi, may I have reviews for this small documentation fix please? I am not a CODETOOLS committer so I may need someone to sponsor this fix.

Since I just built the intellij plugin in 2020.3, I stumbled about a couple of ambiguous infos which are not immediately clear to outsiders.

-> some UI features changed in Intellij
-> Clarified the meaning of JTREG_HOME
-> One thing I was not sure about was the required SDK level to build the plugin. The documentation says "Any JDK 8 is fine" which I took as "JDK8 is required" - proceeded to download JDK 8 but then I was unable to choose this JDK as a SDK for the IDEA JDK. It was, however, happy with a JDK 15 I gave it, and proceeded to build the plugin without any issues. Therefore I changed the sentence to "Any JDK 8++ is a fine choice".

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Referenced JBS issue must only be used for a single change
- [x] Change must be properly reviewed

### Issue
 * [CODETOOLS-7902912](https://bugs.openjdk.java.net/browse/CODETOOLS-7902912): Update IntelliJ Plugin build Readme

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - Committer) ⚠️ Review applies to eda907c821c4dc5c07cf8b2b46f0bc276a7f4251

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jtreg pull/8/head:pull/8` \
`$ git checkout pull/8`

Update a local copy of the PR: \
`$ git checkout pull/8` \
`$ git pull https://git.openjdk.java.net/jtreg pull/8/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8`

View PR using the GUI difftool: \
`$ git pr show -t 8`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jtreg/pull/8.diff">https://git.openjdk.java.net/jtreg/pull/8.diff</a>

</details>

### CODE REVIEW

**Comment by tstuefe** [comment]
Thanks, Maurizio! I took your suggestion. Feel free to sponsor this change, as I said, I am not a committer for codetools.

**Comment by mcimadamore** [comment]
you have to `/integrate` I think then I can sponsor

**Comment by tstuefe** [comment]
Ah, you are right... This got so much easier with Skara.

/integrate

**Pull request closed without merging**
