### PR TITLE
7903191: Fix build with "MAKEFLAGS=-j32".

### PR DESCRIPTION
**Pull request by jankratochvil**
A parallel build needlessly errors out:
/bin/sh: line 5: jtreg/build/classes/com/sun/javatest/regtest/tool/jars.properties: No such file or directory
make: *** [jtreg.gmk:98: jtreg/build/classes/com/sun/javatest/regtest/tool/jars.properties] Error 1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [CODETOOLS-7903191](https://bugs.openjdk.org/browse/CODETOOLS-7903191): Fix build with "MAKEFLAGS=-j32". (**Bug** - P4)

### Reviewers
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jtreg.git pull/72/head:pull/72` \
`$ git checkout pull/72`

Update a local copy of the PR: \
`$ git checkout pull/72` \
`$ git pull https://git.openjdk.org/jtreg.git pull/72/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 72`

View PR using the GUI difftool: \
`$ git pr show -t 72`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jtreg/pull/72.diff">https://git.openjdk.org/jtreg/pull/72.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jtreg/pull/72#issuecomment-1128158648)

### CODE REVIEW

**Review by jonathan-gibbons — CHANGES_REQUESTED** [review]
This would be better/simpler as just `$(MKDIR) -p $(@D)`

**Comment by jankratochvil** [comment]
https://bugs.openjdk.java.net/browse/CODETOOLS-7903191

**Comment by jankratochvil** [comment]
@jonathan-gibbons Hello, is there anything more I should do to get the patch approved? Thanks.

**Comment by jankratochvil** [comment]
@jonathan-gibbons Hello, is there anything more I should do to get the patch approved? Thanks.

**Comment by jankratochvil** [comment]
The builds are still failing with commit 0bb8367d17d4f83a83b2d680badb9c25011534d4 = 2022-12-02

**Comment by jankratochvil** [comment]
The builds are still failing with commit https://github.com/openjdk/jtreg/commit/3c81dd07d221e36acda2958b96dc93540fa2df99 = 2023-05-12

**Review by jonathan-gibbons — APPROVED** [review]

**Pull request closed without merging**
